config/routes.rb
Rails.application.routes.draw do
  root 'cities#index'
  get 'about', to: 'pages#about'

  resources :cities, only: [:index, :show], param: :slug do
    scope module: :cities do
      resources :requests, only: [:show], param: :service_request_id do
        member do
          get ':slug', to: 'requests#show', as: :slug
        end
      end
    end
  end

  resources :requests, only: [:index]

  mount GoodJob::Engine => 'good_job'

  get '/sitemap.xml', to: 'sitemaps#index', defaults: { format: 'xml' }, as: :sitemap
  get '/sitemaps/static.xml', to: 'sitemaps#static', defaults: { format: 'xml' }, as: :static_sitemap
  get '/sitemaps/:slug.xml', to: 'sitemaps#city_index', defaults: { format: 'xml' }, as: :city_sitemap_index
  get '/sitemaps/:slug/:date.xml', to: 'sitemaps#city_day', defaults: { format: 'xml' }, as: :city_day_sitemap

  resolve "ServiceRequest" do |service_request, options|
    service_request.parameterize.merge(controller: 'cities/requests', action: 'show').merge(options)
  end

  direct :github do
    'https://github.com/codeforamerica/open311status'
  end
end

Rails.application.routes.named_routes.url_helpers_module.module_eval do
  def service_request_path(service_request, options = {})
    slug_city_request_path(service_request.city.slug, service_request.service_request_id, service_request.slug, options)
  end

  def service_request_url(service_request, options = {})
    slug_city_request_url(service_request.city.slug, service_request.service_request_id, service_request.slug, options)
  end
end

app/models/city.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cities
#
#  id                        :bigint           not null, primary key
#  service_definitions_count :integer          default(0), not null
#  slug                      :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#
# Indexes
#
#  index_cities_on_slug  (slug) UNIQUE
#

class City < ApplicationRecord
  delegate(*Configuration::ATTRIBUTES, to: :configuration, allow_nil: true)

  has_many :service_requests
  has_many :service_definitions
  has_many :statuses

  has_one_of_many :service_list_status, -> { service_list.order(created_at: :desc) }, class_name: 'Status', inverse_of: :city
  has_one_of_many :service_requests_status, -> { service_requests.order(created_at: :desc) }, class_name: 'Status', inverse_of: :city
  has_many :service_list_statuses, -> { service_list }, class_name: 'Status', inverse_of: :city
  has_many :service_requests_statuses, -> { service_requests }, class_name: 'Status', inverse_of: :city
  has_many :service_list_status_errors, lambda {
    start_floor = 2.days.ago.change(min: 10 * (Time.now.min.to_f / 10).floor)
    service_list.time_periods.errored.where(created_at: start_floor..).order(:time_period)
  }, class_name: 'Status', inverse_of: :city
  has_many :service_request_status_errors, lambda {
    start_floor = 2.days.ago.change(min: 10 * (Time.now.min.to_f / 10).floor)
    service_requests.time_periods.errored.where(created_at: start_floor..).order(:time_period)
  }, class_name: 'Status', inverse_of: :city

  validates :slug, uniqueness: true

  class << self
    def instance(slug)
      where(slug:).first_or_create
    end

    # Loads city configuration data into database
    def load!
      configs = Rails.configuration.cities
      configs.each_key do |slug|
        instance(slug)
      end
    end
  end

  def to_param
    slug
  end

  def api
    @_api ||= City::Api.new(self)
  end

  def configuration
    @_configuration ||= City::Configuration.new(Rails.configuration.cities[slug])
  end

  def uptime_percent(status_type, start: 2.days.ago)
    start_floor = start.change(min: 10 * (Time.now.min.to_f / 10).floor)

    statuses = if status_type == 'service_list'
                 service_list_status_errors
               else
                 service_request_status_errors
               end

    downtime_periods = statuses.group_by(&:time_period).keys.size

    100 - ((downtime_periods.to_f / ((Time.current - start_floor) / 10.minutes)) * 100)
  end
end

app/models/city/api.rb
# frozen_string_literal: true

require 'open311'
require 'hashie'

class City
  class Api
    attr_reader :city

    MAX_AGE = 2.days

    def initialize(city)
      @city = city
    end

    def open311
      @_open311 ||= begin
        api_options = {
          endpoint: city.endpoint,
        }
        api_options[:jurisdiction] = city.jurisdiction if city.jurisdiction
        api_options[:headers] = city.headers if city.headers
        api_options[:format] = city.format if city.format

        ::Open311::Client.new(api_options)
      end
    end

    def services_url
      uri = URI.parse "#{city.endpoint}services.xml"
      uri.query = URI.encode_www_form jurisdiction_id: city.jurisdiction if city.jurisdiction.present?
      uri.to_s
    end

    def requests_url
      uri = URI.parse "#{city.endpoint}requests.xml"
      uri.query = URI.encode_www_form jurisdiction_id: city.jurisdiction if city.jurisdiction.present?
      uri.to_s
    end

    def fetch_service_list
      service_list_data = Status::Telemetry.process('service_list', city:) do
        open311.service_list
      end

      service_list_data = [service_list_data] if service_list_data.is_a?(Hashie::Mash)

      Array(service_list_data).map do |request_data|
        city.service_definitions.find_or_initialize_by(service_code: request_data['service_code']).tap do |service_definition|
          service_definition.raw_data = request_data
          if service_definition.changed?
            service_definition.save!
          else
            service_definition.touch
          end
        end
      end
    end

    def fetch_service_requests(start_param = nil, end_param = nil, collect_telemetry: true)
      start_datetime = start_param.presence || city.service_requests.maximum(:requested_datetime) || MAX_AGE.ago
      end_datetime = end_param.presence

      start_date = start_datetime.utc.xmlschema
      end_date = end_datetime.utc.xmlschema if end_datetime.present?

      if city.requests_omit_timezone
        start_date = start_date.chomp('Z')
        end_date = end_date.chomp('Z') if end_datetime.present?
      end

      requests_data = if collect_telemetry
                        Status::Telemetry.process('service_requests', city:) do
                          if end_datetime
                            open311.service_requests(start_date:, end_date:)
                          else
                            open311.service_requests(start_date:)
                          end
                        end
                      elsif end_datetime
                        open311.service_requests(start_date:, end_date:)
                      else
                        open311.service_requests(start_date:)
                      end

      requests_data = [requests_data] if requests_data.is_a?(Hashie::Mash)

      Array(requests_data).filter_map do |request_data|
        # Some Service Requests may not have a service_request_id
        next if request_data['service_request_id'].blank?

        city.service_requests.find_or_initialize_by(service_request_id: request_data['service_request_id']).tap do |service_request|
          service_request.raw_data = request_data
          if service_request.changed?
            service_request.save!
          else
            service_request.touch
          end
        end
      end
    end
  end
end

app/models/city/configuration.rb
# frozen_string_literal: true

class City
  class Configuration
    include ActiveModel::Model

    ATTRIBUTES = [
      :name,
      :endpoint,
      :jurisdiction,
      :format,
      :headers,
      :notes,
      :requests_limit,
      :requests_omit_timezone,
    ].freeze

    attr_accessor(*ATTRIBUTES)

    def format
      (@format || :json).to_sym
    end

    def headers
      (@headers || {}).symbolize_keys
    end
  end
end

app/controllers/cities/requests_controller.rb
# frozen_string_literal: true

module Cities
  class RequestsController < ApplicationController
    def show
      @service_request = City.find_by!(slug: params[:city_slug]).service_requests.find_by!(service_request_id: params[:service_request_id])
      redirect_to polymorphic_path(@service_request), status: :moved_permanently if @service_request.slug.present? && params[:slug] != @service_request.slug
    end
  end
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  def index
    cities = City.includes(:service_list_status, :service_requests_status, :service_list_status_errors, :service_request_status_errors).order(slug: :asc)
    @cities = CityDecorator.decorate_collection(cities)
    @service_requests = ServiceRequest.includes(:city).by_requested_datetime.limit(100)

    sr_buckets = ServiceRequest.where(city_id: @cities.pluck(:id)).group(:city_id).group_by_hour(:requested_datetime, range: 2.days.ago..Time.current).count
    sr_buckets_by_city = sr_buckets.each_with_object({}) do |(key, value), memo|
      memo[key.first] ||= {}
      memo[key.first][key.second] = value
    end
    @cities.each { |city| city.bucketed_service_requests = sr_buckets_by_city.fetch(city.id, {}) }
  end

  def show
    @city = City.find_by!(slug: params[:slug])
    @service_requests = @city.service_requests.all.by_requested_datetime.limit(100)
  end
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

app/views/cities/_city_row.slim
tr data-city-id=city.id data-target="cities.city"
  = yield

app/views/cities/_city_row_content.slim
td
  strong
    = link_to city.name, city_path(city)

- status = city.service_list_status
- if city.service_list_status.present?
  td data-sort-value="#{status.http_code}-#{status.duration_ms}-#{status.error_message}"
    .text-center
      a(class="btn btn-sm btn-#{ status.label_class }"
        href=city.api.services_url
        rel='noopener nofollow'
        data={ 'bs-toggle': 'tooltip' }
        title=status.description)= status.title
      br
      small
        | #{time_ago_in_words status.created_at} ago
        br
        | #{city.uptime_percent('service_list').round(2)} uptime
- else
  td

- status = city.service_requests_status
- if city.service_requests_status.present?
  td data-sort-value="#{status.http_code}-#{status.duration_ms}-#{status.error_message}"
    .text-center
      a(class="btn btn-sm btn-#{ status.label_class }"
        href=city.api.requests_url
        rel='noopener nofollow'
        data={ 'bs-toggle': 'tooltip' }
        title=status.description)= status.title
      br
      small
        | #{time_ago_in_words status.created_at} ago
        br
        | #{city.uptime_percent('service_requests').round(2)} uptime
- else
  td

td
  | #{city.service_definitions_count} types
td
  span.sparkline data-values=city.bucketed_service_requests.values.join(',')
td
  = city.total_service_requests
td
  = city.min_service_requests
td
  = city.max_service_requests
td
  = city.avg_service_requests

app/views/cities/_service_definitions.slim
table.table.table-bordered.table-striped
  thead
    tr
      th Service Name
      th Description
  tbody
    - service_definitions.find_each do |service_definition|
      tr
        td= service_definition.raw_data['service_name']
        td= service_definition.raw_data['description']

app/views/cities/_service_requests.slim
table.table.table-condensed.table-bordered.table-striped.table-responsive
  thead
    tr
      th Endpoint
      th Service Name
      th Status
      th Description
      th Media
      th Requested At
  tbody
    - ServiceRequestDecorator.decorate_collection(service_requests).each do |service_request|
      tr
        td= service_request.city.name
        td= service_request.status
        td= service_request.raw_data['service_name']
        td= service_request.raw_data['description']
        td
          - if service_request.media_url.present?
            = link_to(service_request.media_url, rel: 'noopener nofollow') do
              = image_tag service_request.media_url, class: 'img-responsive'
        td= link_to "#{time_ago_in_words(service_request.requested_datetime)} ago", service_request

app/views/cities/index.html.slim
ruby:
  provide(:meta_title) { "Open311 Status - 311 API monitoring and analysis" }
.well.mb-3
  strong
    | Scanning #{@cities.size} Open311 endpoints every 10 minutes.
      For endpoint information visit the <a href="http://wiki.open311.org/GeoReport_v2/Servers" rel="noopener">Open311 Wiki</a>.

.card.card-default.mb-3
  .card-header
    h3.card-title Service Requests created during previous 48 hours
  .card-body
    = line_chart @cities.map { |city| { name: city.name, data: city.bucketed_service_requests } }

.card.card-default.mb-3.card-table
  table.table.table-sm.table-bordered.table-striped.tablesorter(data-controller="cities")
    thead
      tr
        th Endpoint
        th Services
        th Requests
        th Request Types
        th data-sorter='false'
          | Submitted requests
          span.badge.badge-info< 48 hours
        th Total
        th Min/Hour
        th Max/Hour
        th Avg/Hour
    tbody
      = render partial: 'city_row_content', layout: 'city_row', collection: @cities, as: :city

h3 Recent Service Requests
.card.card-default.card-table
  = render 'service_requests', service_requests: @service_requests

.text-center.mt-3
  = link_to "View all Service Requests", requests_path, class: 'btn btn-outline-dark'

app/views/cities/show.html.slim
ruby:
  city = @city

  provide(:meta_title) { "Open311 Status - #{city.name}" }
  provide(:meta_description) { "Open311 Status monitors the 311 API endpoint for #{city.name}, providing benchmarks and insights." }

h1= @city.name

.card.card-default.mb-3
  .card-header
    h3.card-title Service Requests created during previous 48 hours
  .card-body
    = line_chart [{ name: city.name, data: city.service_requests.group_by_hour(:requested_datetime, range: 2.days.ago..Time.current).count }]

.card.mb-3
  .card-header
    ul.nav.nav-tabs.card-header-tabs
      li.nav-item role="presentation"
        button class="nav-link active" id="service-requests-tab" data-bs-toggle="tab" data-bs-target="#service-requests-contents" type="button" role="tab" aria-controls="service-requests-contents" aria-selected="false"
          | Service Requests
      li.nav-item role="presentation"
        button class="nav-link" id="service-definitions-tab" data-bs-toggle="tab" data-bs-target="#service-definitions-contents" type="button" role="tab" aria-controls="service-definitions-contents" aria-selected="false"
          | Service Definitions
  .card-body
    .tab-content
      div class="tab-pane show active" id="service-requests-contents" role="tabpanel" aria-labelledby="service-requests-tab" tabindex="0"
        = render 'service_requests', service_requests: @service_requests
      div class="tab-pane" id="service-definitions-contents" role="tabpanel" aria-labelledby="home-tab" tabindex="0"
        = render 'service_definitions', service_definitions: @city.service_definitions